// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketWave.Data;

#nullable disable

namespace TicketWave.Migrations
{
    [DbContext(typeof(TicketWaveContext))]
    [Migration("20250213023148_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("TicketWave.Models.EventTickets", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EventBuyOfferAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventBuyerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventListUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventNumOfTicket")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EventTicketPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventUserContactEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("EventTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
